version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000-3002:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    deploy:
      replicas: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
